# Generated by Django 5.1.3 on 2024-11-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Retiro', 'Retiro'), ('Transferencia', 'Transferencia')], max_length=20),
        ),
        migrations.DeleteModel(
            name='TransactionType',
        ),
    ]
