# Generated by Django 5.1.3 on 2024-11-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_type',
            field=models.CharField(choices=[('Black', 'Black'), ('Gold', 'Gold'), ('Classic', 'Classic')], default='Classic', max_length=20),
        ),
    ]
