# Generated by Django 5.1.3 on 2024-11-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('personal', 'personal'), ('hipotecario', 'hipotecario'), ('prendario', 'prendario')], max_length=50),
        ),
    ]
