# Generated by Django 5.1.3 on 2024-11-16 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_remove_card_expiration_date_card_expiration_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='expiration_month',
        ),
        migrations.RemoveField(
            model_name='card',
            name='expiration_year',
        ),
        migrations.AddField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
